In [1]:
import pandas as pd
import numpy as np

# Number of Ratings per User

In [2]:
#read recent cleaned data
events_df = pd.read_csv('Cleaned_Dataset_With_ID.csv', low_memory=False)
cleaned_people = pd.read_csv('cleaned_people.csv', low_memory= False)
events_df

,Unnamed: 0,name_x,distinct_id,time,ae_session_length,city,region,mp_country_code,locationSetting,notificationSettings,...,active_timespan,average_session_time,country,US,Facebook,Foodie,Google,Unknown,session_id,time_delta
0,0,$ae_first_open,00000000-0000-0000-0000-000000000000,2020-02-13 15:52:50,-1.0,Mumbai,Maharashtra,IN,-1,-1,...,NaN,NaN,INTL,0,0,0,0,0,-1,0
1,1,$ae_first_open,00000000-0000-0000-0000-000000000000,2020-03-08 20:43:54,-1.0,Ahmedabad,Gujarat,IN,-1,-1,...,NaN,NaN,INTL,0,0,0,0,0,-1,0
2,2,AppOpen,000BA5B1-DBEF-414E-ACEC-1A2FCC2053DD,2019-08-23 13:48:32,-1.0,Palo Alto,California,US,-1,-1,...,NaN,NaN,US,1,0,0,0,0,1,0
3,3,Visit Signup/Login Page,000BA5B1-DBEF-414E-ACEC-1A2FCC2053DD,2019-08-23 13:48:35,-1.0,Palo Alto,California,US,-1,-1,...,NaN,NaN,US,1,0,0,0,0,1,0
4,4,$ae_session,000BA5B1-DBEF-414E-ACEC-1A2FCC2053DD,2019-08-23 13:49:02,30.1,Palo Alto,California,US,-1,-1,...,NaN,NaN,US,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190366,190366,Feed - Scroll Down,xbarbarazhong@gmail.com_6704,2019-12-12 14:29:23,-1.0,Portland,Oregon,US,-1,-1,...,NaN,NaN,US,1,0,0,0,0,29813,0 days 00:03:08
190367,190367,Profile - Change Section,xbarbarazhong@gmail.com_6704,2019-12-12 14:29:28,-1.0,Portland,Oregon,US,-1,-1,...,NaN,NaN,US,1,0,0,0,0,29813,0 days 00:03:08
190368,190368,$ae_session,xbarbarazhong@gmail.com_6704,2019-12-12 14:30:54,190.4,Portland,Oregon,US,-1,-1,...,NaN,NaN,US,1,0,0,0,0,29813,0 days 00:03:08
190369,190369,AppOpen,yoon.s.jeong@gmail.com_6485,2019-10-09 11:12:29,-1.0,Chicago,Illinois,US,-1,-1,...,NaN,NaN,US,1,0,0,0,0,29814,0
190370,190370,$ae_session,yoon.s.jeong@gmail.com_6485,2019-10-09 11:13:09,41.3,Chicago,Illinois,US,-1,-1,...,NaN,NaN,US,1,0,0,0,0,29814,0

In [3]:
#creating dictionary with distinct id and number of ratings
number_ratings_dict = events_df[events_df['name_x'] == 'Rating Flow - Complete'].groupby('distinct_id').count()['name_x'].to_dict()
number_ratings_dict

{'000BA5B1-DBEF-414E-ACEC-1A2FCC2053DD': 1,
 '0025A8A4-2590-4ECA-8CE8-419D710AE46F': 1,
 '00CE2C99-8AC3-433E-8611-944CAC725EA5': 2,
 '00D88292-02E5-4966-8079-DB96622C3970': 5,
 '01A0296F-17C9-4369-AA6E-D3536C94B986': 4,
 '0279E9CC-C4C8-4593-9E2B-38A29E928ED3': 5,
 '04242E1E-1CF2-493A-AB13-DE2FB7CB4029': 4,
 '0428E3AC-F7C3-491D-99A9-CDF00B57C806': 2,
 '0445D8B4-9A92-48D8-B585-F1AA4D00BF22': 1,
 '058A7643-8323-4C77-9A8D-5FEC74ED98C7': 3,
 '06734B33-C7EE-4CA7-9643-7C27BB6B509F': 2,
 '0785BD4E-3F03-4069-B360-F5300B407605': 3,
 '07EEAF0F-39DF-4DF4-8C4B-FC667151786E': 1,
 '09353F2A-56B0-4BF8-B532-C8B9B25BCC80': 48,
 '09400B26-4074-4DA6-8109-045B25D0B949': 3,
 '0A9EAE40-440D-4292-91CE-1817EC1C5E82': 15,
 '0BC21542-59E3-4107-AB10-ABFCFF6393B6': 6,
 '0C867A10-319E-43EE-BE0C-A1C2C4E66059': 2,
 '0C954A3F-0AB6-4D12-B4E9-D916C95B0C6E': 10,
 '0E7476C1-FCFA-48A7-AC73-EE86EA15677A': 1,
 '0F949AE7-2983-47AC-B81C-946ED693F153': 1,
 '0FA1DA92-5CED-4927-AA0A-05C26D80A68B': 5,
 '10ADF4BA-C7B1-4E26-9C48-C10D651BE26A': 1,
 '136574A3-1D0C-4260-9F6E-8CEB1953E2C9': 1,
 '14AF7B99-6CB0-42BC-8FD7-4D7172595D4F': 25,
 '14E548F9-6049-43B4-91FC-447A6F3918B7': 14,
 '151EFB59-2F41-4E9F-AF22-9C05C9EC6030': 3,
 '1579493E-F022-4CAD-B274-63FD1D713206': 1,
 '17D4E95E-9D83-45D9-8644-DFF54E415C3D': 1,
 '18D5EA29-D0F8-4885-A521-89BBF49A6409': 1,
 '19F84BA9-738A-42F1-AB91-886ABD5A616E': 1,
 '1A93A550-1639-4946-A522-ECDB53A5665D': 3,
 '1FE9F883-78D5-4DB6-9E1F-30FE4B27A895': 1,
 '20C8764A-95E6-4074-8466-CAF1F0437F90': 23,
 '2109587D-3F4B-4AF0-94B4-C3CF07FBCDBB': 2,
 '219258CD-8D3E-4C37-8AB8-7D9D4F6E90BB': 8,
 '22622ECB-57F3-4E80-A9AE-9F2A8CAA838B': 3,
 '23997D51-7E34-4EC2-A069-39BAF78E77BD': 2,
 '23DCFDAD-B8FF-4BFE-885D-CF542CE0B030': 3,
 '24686D2D-2E00-49C0-9F49-230AB3AC50D0': 1,
 '250E5092-AD4D-45B4-9B9E-3C5445343A1C': 1,
 '2531FF09-FF50-4BF5-967F-B03FBB51FFDD': 1,
 '261d8b15e62a5dce': 2,
 '27968824-675F-4995-979B-44776827567C': 2,
 '2838A12C-D21B-4B9C-859D-CD5C680CDB4C': 1,
 '291D4DF8-CD30-45B0-A460-48CEB7907870': 2,
 '2BC5FCAE-8AE9-4F03-8A5B-8302B46015ED': 5,
 '2ED8AA78-8015-4812-AB34-CCA9909AC090': 9,
 '316986A2-AF60-4591-8E3B-CC1DEE2A3DC3': 1,
 '3408a5eb77f5751e': 24,
 '35E2002C-4527-4BE0-A29F-37C2C66AF4EA': 3,
 '36B28ADA-43BD-42B0-A0F1-AD4494A141D0': 1,
 '3746E57C-9D7E-42BC-81D7-16B0269E70ED': 13,
 '39FFCC6B-F315-45C7-94CE-64272019E4A4': 3,
 '3E3A9831-2214-4F86-B6C5-F50E29D7BA01': 1,
 '3E4D1529-15BA-4D33-A487-B066F8FF4F01': 12,
 '3e0e9c4cf9952060': 3,
 '40AA99CE-F4A4-4F98-B015-937CC3077986': 4,
 '41AB9E63-B055-4995-B4DE-D346ADA7212D': 13,
 '4223E0EB-8244-44C0-9E79-B26994955A20': 4,
 '437119bf2f2ef95b': 1,
 '45891A27-B088-4549-8DB8-3C3B4F66F4ED': 1,
 '46B0ACD6-074D-47E2-BC21-E63D5681FB89': 1,
 '46D2D266-5705-4E83-9678-381D709C082C': 6,
 '4749ABC7-01BD-4E5E-A957-D22EDDBCD76A': 21,
 '4BFB060F-4376-4913-90AB-F1B2AB36993C': 3,
 '4D8FF6AD-B718-49D8-B6A5-88C0F53CCBB6': 1,
 '4FFC33C2-7318-4414-8137-00945B858EB2': 2,
 '5025CE2B-BB9E-473B-AF30-0030520E5B04': 1,
 '52774481-EECA-4703-8F31-F634B24773BE': 2,
 '52BCDFC4-B5C0-4FAF-AFFF-3B504A5D4932': 5,
 '556B7571-0004-4850-BFB5-AD845457A6B6': 1,
 '575B9B98-4BBD-4B3C-AFEA-2493D83068CA': 1,
 '5773BEF9-C458-4142-9C06-BB044ECEA730': 1,
 '580B4B43-AD04-47B6-8B1A-D911C2C7496C': 3,
 '582FE9F6-5A27-4FC0-8F7D-CCEA4AE76AF8': 56,
 '5A25D893-F12F-4DB8-BFE6-99BAD3451788': 5,
 '5EC56924-5A83-4C09-A8E8-97602CBE9B0F': 1,
 '5F448B92-AD7E-486A-8F3B-F0663054F358': 2,
 '601C0F85-3DF5-4F58-A101-2BE1D52176BC': 1,
 '611FE09B-7D6D-4A6C-BA71-7020338FD35B': 3,
 '6147C3FD-524D-4F0F-AA58-4F9F3D89561A': 8,
 '61A36664-5201-43C4-BC4E-65FCF61F87F3': 2,
 '622FF07E-2381-4D5F-A33A-A9938A29DE0F': 1,
 '625E1E17-4CB6-4F1F-9E51-965F29575168': 1,
 '629987EB-EE9B-4162-A12B-20152B9F57E4': 5,
 '63298C70-0C9C-4ED3-8CDA-4439E4AFD7F6': 1,
 '640C957B-A1F1-4C97-8777-D93C155A5B56': 1,
 '6447A908-7FC0-4E67-952A-D137395942FB': 2,
 '644813C2-FA10-485A-8347-E1D942C8DAD8': 1,
 '64A2393B-B6BC-4B82-A3D8-3D8716B4F7B9': 3,
 '65A8D010-EABB-45A9-9C9A-F047E28C3DEB': 4,
 '6624A41B-85EB-40A6-B88F-43C5D6508F58': 1,
 '66E288CE-B7D7-492C-BE11-85B70167180F': 1,
 '68B8BC7A-5AB2-4BA0-9E07-5DB995CE960B': 1,
 '6902A4A8-5656-450E-A802-337E23CACC42': 2,
 '6915BCA4-9430-4A44-8159-D17E428B2CBE': 1,
 '6959B13E-2C95-4D4B-AB74-C39EE48F6D01': 3,
 '69A409B6-41AE-4B48-A862-E3505A63ED18': 24,
 '6B6F3027-5AD3-49B3-B0F3-733EE1759217': 1,
 '6D4A95E4-A8BD-49DB-B95F-617C9FD3C2F7': 2,
 '6b8d8f53a21c9f96': 6,
 '70CEFB37-3D4D-4131-AECF-3F9F84809C2A': 4,
 '720602BB-B944-4D6D-B330-A96FB658CD21': 1,
 '72F5C0AE-66CA-4A79-B9FD-AC3570E1B133': 3,
 '73B107E7-1170-48E8-839A-91CDBA40510F': 10,
 '7466E480-A994-4CFC-BAFD-C9B96841A8A3': 48,
 '762A8B14-8327-4A97-A7FD-41863058A3BD': 1,
 '77501C28-F0A4-4146-9B6F-0AC86F88D54B': 4,
 '78B3BC86-1FEB-4CFE-8ED7-1FBB59A0FE12': 7,
 '78D35D7D-A097-468F-AEF3-F93921366BD3': 1,
 '78a0758ad87e47b6': 3,
 '7A2BC5BC-E8C8-409D-97E6-6BC97BB9E522': 3,
 '7A862933-DD3C-46A8-BF85-9695CFB22929': 1,
 '7AEB5323-9ABA-4010-8BE4-681479D29EDB': 2,
 '7BBBD941-07FD-47EE-B26B-1E63E4C973DE': 1,
 '7C1A30B3-F28E-4ED7-9A4E-7298A69D27DF': 82,
 '7DBBA8FA-9050-4E9E-A779-F12643B7FBF5': 65,
 '7E198BF5-6141-4661-891B-76D669619250': 1,
 '7F1394A1-0A1C-4E45-B6A5-F6270B2A9030': 6,
 '7F31A65B-DA2C-4972-AAC0-D73A77B1183F': 14,
 '8375E983-1377-4817-9B28-0D7BC042472D': 10,
 '84ADB356-5FB6-46F9-A7AB-66ED89C8C6C8': 1,
 '85189866-1049-49E6-A4BE-1E6EBF86C895': 1,
 '8558FBF3-3F57-4EE5-8C9C-D51BB742A6C2': 6,
 '862C54BF-92DB-4056-B369-57C94583CDFE': 2,
 '874b20ef7521280e': 35,
 '87F52467-72C8-4E6B-80FD-411BD3809F04': 3,
 '885430F9-9470-46A2-9AAB-0AF9FF3DBC7C': 1,
 '8906CF95-792C-4278-B773-2814117610E8': 1,
 '89685335b58ddaee': 4,
 '8B0BD6A8-36BC-417D-BD59-AF41E4735CBF': 9,
 '8B11F17E-4E53-48CE-80B9-A3F57071B428': 2,
 '8EED1536-33AB-443D-B2BF-E6B0D04D33BE': 1,
 '920468BC-BA45-4031-9508-4BFB666ACE8D': 1,
 '92511852-6A4F-430D-9D89-E390095A49BA': 6,
 '930353FD-A325-4660-AB5C-3C90D6D7335E': 9,
 '948118ED-04FA-4F48-ACCA-452AD6736C93': 45,
 '974D2041-7033-4FD6-9E09-7C076049D61F': 2,
 '989DA20C-D812-458F-B928-B0A78C1C1096': 3,
 '9B853C55-9CFA-4A08-94D4-B3B53D3E91EE': 7,
 '9CBB0959-6AFA-4FF6-8854-526B3DE64F78': 46,
 '9DEF046A-E9E4-4E32-B957-CF96DF6AEB4B': 11,
 '9E77BD48-7F78-4507-92C6-A14D7727828B': 1,
 '9F0FD987-9D7B-49E7-A4CF-9D2AA0473798': 2,
 '9F6F433B-3632-4884-9949-B906A41AA120': 3,
 'A3B26DEF-365A-42FA-A387-85C2BCB533A6': 2,
 'A81D6093-780C-4BC8-868F-3F4A31F81EA9': 1,
 'A92760DD-3852-4069-AE64-57C6A96BDC07': 4,
 'A9A16F68-BD8B-4BC8-9825-6C0B0A5FC2FA': 1,
 'AA1A7744-436D-413C-BD24-3CAFAC1FE2B8': 1,
 'AB6B3CAE-F30A-407D-9527-F2928FAC752B': 11,
 'ABAD11BF-7C8B-4605-9E69-7A107DF0497C': 5,
 'ABC40A67-D5D6-495D-AF3B-19A8D587FD4E': 2,
 'ABE1FFFF-CFBA-4EF5-ABDF-9DB32C70F9A3': 2,
 'ABE32EEA-A8FC-457F-B439-A264183C910B': 2,
 'ADA6E194-7B22-42C7-991E-0C5191F79271': 1,
 'AE0112E5-7D72-4776-9A1B-C034821BFC31': 1,
 'AEE97BB5-ABF3-4D61-9118-9ECCE04EE5C2': 1,
 'B2DD3857-E455-4A0C-BA52-75BD79228B0B': 31,
 'B395D3FC-B576-4091-B0C6-E820445551C2': 2,
 'B5B13E38-F2A1-45BF-97D7-4FF57D2735B0': 1,
 'B77D7A2F-834A-40A8-9331-18C668C6EF09': 5,
 'B789F4A1-FFE8-4506-82FB-F3E7A7F469DF': 1,
 'B9379DAC-C180-479A-AC1E-AFC5E825C230': 2,
 'BA5E7127-7BB0-4F1B-9D28-6A379EF71307': 1,
 'BA8D8112-18B9-4B99-B63B-E12DE4841B9A': 3,
 'BAC32AD2-3FEA-44FC-A8D7-2B9A81F28ACE': 1,
 'BB9376AC-0071-46D3-9B66-FE8CBFFE0576': 1,
 'BCC5CB2F-0A12-4335-8660-C71C0393F318': 1,
 'BCE5AB85-7BE6-4BAF-AA49-557013451320': 1,
 'BD5966E0-75A6-4640-9B61-388008E081AD': 9,
 'BFA9B0AC-92A7-451E-B220-FC36F304B1BA': 4,
 'Benshields8962@yahoo.com_5456': 4,
 'C282D117-AD97-4512-91D5-9D24F5B0EBE1': 5,
 'C351D104-D1B8-412E-BD2B-C279A50B80DE': 1,
 'C6BAB5DD-3F2C-4CDA-B5B9-9B3BD1265AD1': 3,
 'C71E1692-96D9-4F03-B8E0-DA0DC05170EB': 2,
 'C7265E6B-3EEC-43FB-AE98-D240CFB0DD6D': 2,
 'C7A0DFE7-72B2-4FB7-B7F6-9A49D6EBAA0B': 1,
 'C92CC8A2-E0FD-4789-B53A-12BF94B213DF': 19,
 'C978938A-F240-4FF6-B7B5-1943A5041774': 58,
 'CA987ECF-0C93-40F8-A336-D58E80392B2C': 2,
 'CD100902-36B0-4AE4-A075-E6E427649309': 1,
 'CDEBF969-3063-44C2-B9A2-18A8197343F0': 1,
 'CE103DF8-829A-4311-AE69-A120CADCF639': 1,
 'CE1E3FC3-FC94-4FB0-AC67-6FA248D8A135': 9,
 'CFB64EC1-79BE-49D9-A1A7-18BD9CDD549B': 4,
 'Chikumbomaxine@gmail.com_6500': 2,
 'D0E54EA6-2998-4D21-A5D5-120D3227D58E': 1,
 'D2BAD87E-3389-4398-B9A2-EEC7CEE93DBB': 1,
 'D3264EA1-91F5-4AB1-824C-39BC50BEA979': 10,
 'D3DB4F69-2173-4C5C-A3A8-179C9D0EBDEB': 2,
 'D7ABC103-E971-41DB-BFCD-ACDF8F95C0DE': 1,
 'D90BDBAC-3887-4083-B082-29EFE6AD0B78': 2,
 'D979B554-8A1A-4764-A662-AA179A8B2175': 1,
 'DB387857-02A8-4BBF-B299-450EDB8C9560': 1,
 'DC0E0F57-C65A-4614-9D31-B01BA9E6EB7D': 5,
 'DD19DD90-BB46-41AD-AC1C-8D163196902D': 8,
 'DF1854AD-A794-4C6F-B282-547CA9EE6E9D': 4,
 'Dzavala@uchicago.edu_118': 25,
 'E1A6A21B-DA7E-4D8B-AB87-9ECA71047891': 20,
 'E2DF1043-8069-4E8A-B8BA-DFCF2BA26965': 1,
 'E693971A-BD3D-4E08-8E34-676099B2C496': 7,
 'E81BB201-7582-4A4A-82C1-47F29FE0A013': 2,
 'E9B4B2BA-03B6-4DC2-991C-0177970A5EBF': 1,
 'EA468CEC-7140-49AE-9AD2-66BFFE9483C9': 1,
 'EB36EBD8-E1E8-483A-9FB5-1BD9EEF8AFA7': 1,
 'EB840084-630C-4FB5-98F8-5DF00E399099': 1,
 'EC17F13A-0993-405D-B4D7-448A7BF71F25': 1,
 'EC1BF644-BB08-4513-AC4B-F32EDEFA92D1': 1,
 'ECDB97DA-AADC-4940-A5C8-F610501EC0A0': 7,
 'EF1C1322-6470-4993-9D8C-BB91D92AF01F': 1,
 'F1ED6532-1BE7-4FCD-9E67-12621B03E171': 3,
 'F357F436-86BD-4A6A-924C-C510FBDFCF2E': 1,
 'F3ACF717-1FF0-42D6-9B87-93A534B0DB80': 1,
 'F4FB8E90-F16D-4A1E-8068-291DD7645B22': 1,
 'F6935507-791A-40E8-B61A-534FCF4748E7': 2,
 'F7898AF1-2067-4303-8AC6-BE7ADCD4C078': 1,
 'F862CA72-E63F-47BA-8C9C-33E242F13A6E': 1,
 'F9B03139-3FE4-4A39-9FE5-91BC5CDA3CDD': 1,
 'FAF3EF87-4A34-4985-9CF8-CD403FCD7F7D': 3,
 'FB7D5E06-4AC0-448B-A181-ED893B3F78A3': 1,
 'FC9EF9C7-23BA-4B05-93EC-CC18F95EDEC1': 2,
 'FCF89FCA-EF91-41FD-BBAE-E618D35C83B3': 3,
 'FD0223C8-89BB-4E6F-9BEC-F34B6CA696D1': 1,
 'FF24533D-A130-4DD6-AC00-8DC0DB23C805': 1,
 'Gh@g.com_5858': 4,
 'ab.codebase@gmail.com_52': 89,
 'addidas23@gmail.com_139': 3,
 'amitku55033@gmail.com_5857': 1,
 'andrewjabara@gmail.com_311': 8,
 'bh@gmail.com_5497': 46,
 'd2baa8a36ca0137d': 79,
 'eemilyshenn@gmail.com_227': 101,
 'girlsrule728@gmail.com_180': 4,
 'harshil1088@gmail.com_51': 12,
 'hr@gmail.com_87': 130,
 'jackjr85.jg@gmail.com_5519': 2,
 'jonathangizmo@gmail.com_6611': 14,
 'katieflee22@gmail.com_6840': 3,
 'mai.nabar@gmail.com_104': 16,
 'nb@gmail.com_93': 439,
 'nkquynhv@gmail.com_6698': 3,
 'omaserkamalo@yahoo.com_5936': 1,
 'rebeccaqian@uchicago.edu_271': 1,
 'richard.z.wu@gmail.com_136': 118,
 'rishi.r.krishnan@gmail.com_80': 2,
 'scao21@uchicago.edu_116': 47,
 'spatel@gmail.com_53': 19,
 'sreekanthreddytrnt@gmail.com_6668': 1,
 'surelyfoodhere@gmail.com_318': 1,
 'vaibhavverma9@uchicago.edu_56': 125,
 'willwojt@gmail.com_6868': 7}

In [4]:
cleaned_people

,Unnamed: 0,distinct_id,ae_total_app_session_length,name,country_code,auth_provider,ae_total_app_sessions,timezone,last_seen,ios_app_version,ios_version,ios_device_model,ios_lib_version,ae_first_app_open_date,active_timespan,average_session_time
0,0,hr@gmail.com_87,345721,Harshil Raval,IN,Foodie,1759,Asia/Kolkata,2020-03-03 06:08:32+00:00,2.5.0,13.2.3,"iPhone9,3",3.4.9,2019-05-30 01:08:51.984962560+00:00,278 days 04:59:40.015037440,196.544059
1,1,E2D9AB63-1718-4D1E-936F-10BE1D889989,4412,Theodore Wu,US,Google,59,America/Los_Angeles,2019-09-08 03:15:47+00:00,2.0.5,13.1,"iPhone9,1",3.4.4,2019-04-22 20:34:46+00:00,138 days 06:41:01.000000000,74.779661
2,2,vaibhavverma9@gmail.com_56,71430,Vaibhav Verma,IN,Foodie,621,Asia/Kolkata,2019-04-15 15:18:25+00:00,1.3.7,12.2,"iPhone7,1",3.3.3,2019-05-30 01:08:51.984962560+00:00,-45 days +14:09:33.015037440,115.024155
3,3,0C954A3F-0AB6-4D12-B4E9-D916C95B0C6E,12836,Tiffany Qi,US,Facebook,77,America/Los_Angeles,2019-11-09 18:33:06+00:00,2.1.6,13.1.3,"iPhone9,3",3.4.4,2019-05-01 06:57:08+00:00,192 days 11:35:58.000000000,166.701299
4,4,addidas23@gmail.com_139,2066,Nathan Nangia,US,Foodie,39,America/Chicago,2020-03-18 15:09:21+00:00,2.5.4,13.4,"iPhone11,2",3.4.9,2019-05-30 01:08:51.984962560+00:00,293 days 14:00:29.015037440,52.974359
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,176,52774481-EECA-4703-8F31-F634B24773BE,161801,Reyna Huang,US,Facebook,1168,America/New_York,2020-02-23 00:59:33+00:00,2.4.7,13.3.1,"iPhone12,1",3.4.4,2019-02-08 14:15:24+00:00,379 days 10:44:09.000000000,138.528253
177,177,F4B6EE31-E835-4C5D-8387-456DFF4E9A3D,8308,Christine Duke,US,Unknown,53,America/Chicago,2020-03-21 16:43:15+00:00,2.5.0,13.3.1,"iPhone12,3",3.4.9,2018-12-03 21:10:02+00:00,473 days 19:33:13.000000000,156.754717
178,178,04ADA4C3-9212-49DA-B600-67A8403D69C3,2283,Alexandria Ma,US,Unknown,45,America/Chicago,2020-01-19 01:41:22+00:00,2.3.3,13.2,"iPhone11,8",3.4.4,2019-06-11 14:14:02+00:00,221 days 11:27:20.000000000,50.733333
179,179,619EECB8-EA49-493B-9048-4EAB912BF98E,4227,Lucy Li,US,Facebook,67,America/Chicago,2019-12-12 03:35:49+00:00,2.3.3,13.2,"iPhone12,3",3.4.4,2019-05-23 13:42:40+00:00,202 days 13:53:09.000000000,63.089552
180,180,1D828D20-752E-45B9-966A-C893DF041CFE,6065,Kecheng Liu,US,Google,85,America/Chicago,2020-02-25 00:36:12+00:00,2.4.7,13.3.1,"iPhone11,2",3.4.4,2019-03-09 14:26:38+00:00,352 days 10:09:34.000000000,71.352941

In [5]:
#creating df with just distinct_id and mapping ratings to each distinct id, filling in Nans with 0
short_df = cleaned_people[['distinct_id']]
short_df['number_ratings'] = short_df['distinct_id'].map(number_ratings_dict)
short_df = short_df.fillna(0)
short_df

C:\Users\annaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

                              distinct_id  number_ratings
0                         hr@gmail.com_87           130.0
1    E2D9AB63-1718-4D1E-936F-10BE1D889989             0.0
2              vaibhavverma9@gmail.com_56             0.0
3    0C954A3F-0AB6-4D12-B4E9-D916C95B0C6E            10.0
4                 addidas23@gmail.com_139             3.0
..                                    ...             ...
176  52774481-EECA-4703-8F31-F634B24773BE             2.0
177  F4B6EE31-E835-4C5D-8387-456DFF4E9A3D             0.0
178  04ADA4C3-9212-49DA-B600-67A8403D69C3             0.0
179  619EECB8-EA49-493B-9048-4EAB912BF98E             0.0
180  1D828D20-752E-45B9-966A-C893DF041CFE             0.0

[181 rows x 2 columns]

In [6]:
sum(events_df[events_df['distinct_id']=='hr@gmail.com_87']['name_x']=='Rating Flow - Complete')

130

In [7]:
sum(short_df['distinct_id']!=cleaned_people['distinct_id'])

0

In [8]:
# drop 'distinct_id' column from short_df and then append to the original dataframe

short_df = short_df.drop(columns = ['distinct_id'])
cleaned_people = pd.concat([cleaned_people, short_df], axis=1)

In [9]:
cleaned_people

,Unnamed: 0,distinct_id,ae_total_app_session_length,name,country_code,auth_provider,ae_total_app_sessions,timezone,last_seen,ios_app_version,ios_version,ios_device_model,ios_lib_version,ae_first_app_open_date,active_timespan,average_session_time,number_ratings
0,0,hr@gmail.com_87,345721,Harshil Raval,IN,Foodie,1759,Asia/Kolkata,2020-03-03 06:08:32+00:00,2.5.0,13.2.3,"iPhone9,3",3.4.9,2019-05-30 01:08:51.984962560+00:00,278 days 04:59:40.015037440,196.544059,130.0
1,1,E2D9AB63-1718-4D1E-936F-10BE1D889989,4412,Theodore Wu,US,Google,59,America/Los_Angeles,2019-09-08 03:15:47+00:00,2.0.5,13.1,"iPhone9,1",3.4.4,2019-04-22 20:34:46+00:00,138 days 06:41:01.000000000,74.779661,0.0
2,2,vaibhavverma9@gmail.com_56,71430,Vaibhav Verma,IN,Foodie,621,Asia/Kolkata,2019-04-15 15:18:25+00:00,1.3.7,12.2,"iPhone7,1",3.3.3,2019-05-30 01:08:51.984962560+00:00,-45 days +14:09:33.015037440,115.024155,0.0
3,3,0C954A3F-0AB6-4D12-B4E9-D916C95B0C6E,12836,Tiffany Qi,US,Facebook,77,America/Los_Angeles,2019-11-09 18:33:06+00:00,2.1.6,13.1.3,"iPhone9,3",3.4.4,2019-05-01 06:57:08+00:00,192 days 11:35:58.000000000,166.701299,10.0
4,4,addidas23@gmail.com_139,2066,Nathan Nangia,US,Foodie,39,America/Chicago,2020-03-18 15:09:21+00:00,2.5.4,13.4,"iPhone11,2",3.4.9,2019-05-30 01:08:51.984962560+00:00,293 days 14:00:29.015037440,52.974359,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,176,52774481-EECA-4703-8F31-F634B24773BE,161801,Reyna Huang,US,Facebook,1168,America/New_York,2020-02-23 00:59:33+00:00,2.4.7,13.3.1,"iPhone12,1",3.4.4,2019-02-08 14:15:24+00:00,379 days 10:44:09.000000000,138.528253,2.0
177,177,F4B6EE31-E835-4C5D-8387-456DFF4E9A3D,8308,Christine Duke,US,Unknown,53,America/Chicago,2020-03-21 16:43:15+00:00,2.5.0,13.3.1,"iPhone12,3",3.4.9,2018-12-03 21:10:02+00:00,473 days 19:33:13.000000000,156.754717,0.0
178,178,04ADA4C3-9212-49DA-B600-67A8403D69C3,2283,Alexandria Ma,US,Unknown,45,America/Chicago,2020-01-19 01:41:22+00:00,2.3.3,13.2,"iPhone11,8",3.4.4,2019-06-11 14:14:02+00:00,221 days 11:27:20.000000000,50.733333,0.0
179,179,619EECB8-EA49-493B-9048-4EAB912BF98E,4227,Lucy Li,US,Facebook,67,America/Chicago,2019-12-12 03:35:49+00:00,2.3.3,13.2,"iPhone12,3",3.4.4,2019-05-23 13:42:40+00:00,202 days 13:53:09.000000000,63.089552,0.0
180,180,1D828D20-752E-45B9-966A-C893DF041CFE,6065,Kecheng Liu,US,Google,85,America/Chicago,2020-02-25 00:36:12+00:00,2.4.7,13.3.1,"iPhone11,2",3.4.4,2019-03-09 14:26:38+00:00,352 days 10:09:34.000000000,71.352941,0.0

# Final Function

In [5]:
def ratings(events, people):
    #creating dictionary with distinct id and number of ratings
    number_ratings_dict = events[events['name_x'] == 'Rating Flow - Complete'].groupby('distinct_id').count()['name_x'].to_dict()
    
    #creating df with just distinct_id and mapping ratings to each distinct id, filling in Nans with 0
    short_df = people[['distinct_id']]
    short_df['number_ratings'] = short_df['distinct_id'].map(number_ratings_dict)
    short_df = short_df.fillna(0)
    
    # drop 'distinct_id' column from short_df and then append to the original dataframe
    short_df = short_df.drop(columns = ['distinct_id'])
    people = pd.concat([people, short_df], axis=1)
    
    return people

In [6]:
ratings(events_df, cleaned_people)

C:\Users\annaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

,Unnamed: 0,distinct_id,ae_total_app_session_length,name,country_code,auth_provider,ae_total_app_sessions,timezone,last_seen,ios_app_version,ios_version,ios_device_model,ios_lib_version,ae_first_app_open_date,active_timespan,average_session_time,number_ratings
0,0,hr@gmail.com_87,345721,Harshil Raval,IN,Foodie,1759,Asia/Kolkata,2020-03-03 06:08:32+00:00,2.5.0,13.2.3,"iPhone9,3",3.4.9,2019-05-30 01:08:51.984962560+00:00,278 days 04:59:40.015037440,196.544059,130.0
1,1,E2D9AB63-1718-4D1E-936F-10BE1D889989,4412,Theodore Wu,US,Google,59,America/Los_Angeles,2019-09-08 03:15:47+00:00,2.0.5,13.1,"iPhone9,1",3.4.4,2019-04-22 20:34:46+00:00,138 days 06:41:01.000000000,74.779661,0.0
2,2,vaibhavverma9@gmail.com_56,71430,Vaibhav Verma,IN,Foodie,621,Asia/Kolkata,2019-04-15 15:18:25+00:00,1.3.7,12.2,"iPhone7,1",3.3.3,2019-05-30 01:08:51.984962560+00:00,-45 days +14:09:33.015037440,115.024155,0.0
3,3,0C954A3F-0AB6-4D12-B4E9-D916C95B0C6E,12836,Tiffany Qi,US,Facebook,77,America/Los_Angeles,2019-11-09 18:33:06+00:00,2.1.6,13.1.3,"iPhone9,3",3.4.4,2019-05-01 06:57:08+00:00,192 days 11:35:58.000000000,166.701299,10.0
4,4,addidas23@gmail.com_139,2066,Nathan Nangia,US,Foodie,39,America/Chicago,2020-03-18 15:09:21+00:00,2.5.4,13.4,"iPhone11,2",3.4.9,2019-05-30 01:08:51.984962560+00:00,293 days 14:00:29.015037440,52.974359,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176,176,52774481-EECA-4703-8F31-F634B24773BE,161801,Reyna Huang,US,Facebook,1168,America/New_York,2020-02-23 00:59:33+00:00,2.4.7,13.3.1,"iPhone12,1",3.4.4,2019-02-08 14:15:24+00:00,379 days 10:44:09.000000000,138.528253,2.0
177,177,F4B6EE31-E835-4C5D-8387-456DFF4E9A3D,8308,Christine Duke,US,Unknown,53,America/Chicago,2020-03-21 16:43:15+00:00,2.5.0,13.3.1,"iPhone12,3",3.4.9,2018-12-03 21:10:02+00:00,473 days 19:33:13.000000000,156.754717,0.0
178,178,04ADA4C3-9212-49DA-B600-67A8403D69C3,2283,Alexandria Ma,US,Unknown,45,America/Chicago,2020-01-19 01:41:22+00:00,2.3.3,13.2,"iPhone11,8",3.4.4,2019-06-11 14:14:02+00:00,221 days 11:27:20.000000000,50.733333,0.0
179,179,619EECB8-EA49-493B-9048-4EAB912BF98E,4227,Lucy Li,US,Facebook,67,America/Chicago,2019-12-12 03:35:49+00:00,2.3.3,13.2,"iPhone12,3",3.4.4,2019-05-23 13:42:40+00:00,202 days 13:53:09.000000000,63.089552,0.0
180,180,1D828D20-752E-45B9-966A-C893DF041CFE,6065,Kecheng Liu,US,Google,85,America/Chicago,2020-02-25 00:36:12+00:00,2.4.7,13.3.1,"iPhone11,2",3.4.4,2019-03-09 14:26:38+00:00,352 days 10:09:34.000000000,71.352941,0.0